begin;

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.notes enable row level security;

revoke all privileges on table public.notes from public, anon, authenticated;
revoke all privileges on sequence public.notes_id_seq from public, anon, authenticated;
grant select on table public.notes to service_role;

commit;

-- 2단계 학습용 테이블 정의만 저장소에 기록합니다.
-- owner_id는 uuid이지만 auth.users 외래키를 걸지 않습니다.
-- anon/authenticated에는 SELECT 정책을 만들지 않습니다.
-- 가상 메모 본문 네 건은 Supabase SQL Editor에서만 입력하고 이 파일에는 평문을 남기지 않습니다.
-- 3단계 전까지 /api/notes는 공개 주소이므로 실제 개인정보나 비밀 자료를 저장하지 않습니다.
